### ISSUE TITLE
Error while connecting.

### ISSUE THREAD

**Issue by DinosIpiotis** [iTwin/itwin-unreal-plugin#10]
Good morning all, 

I have installed the plugin and try to stream a model. I have created an App although I don't know if I need to tie the app to the iModel and how to do this. Either way, I have filled the information and when it opens the webpage I receive the following:

![image](https://github.com/user-attachments/assets/3ccec7a1-ed8e-403b-adcd-8983af8377f0)

Any advice is appreciated.

**Comment by Julot94** [comment]
Hello,
Did you follow the instructions from section _2. Using the installed iTwin plugin inside Unreal Engine_, in the Readme?
If yes, which way did you choose to propagate your iTwin App ID?
Thanks

**Comment by DinosIpiotis** [comment]
This is where my issue lies, I have followed the instructions in Section 2. I have created an App with the URI provided. I am adding this in the relevant fields but still it does not connect. 
I will review the process of the app association with the iTwin model as I believe my mistake sits there. Any further advice is appreciated.

**Comment by DinosIpiotis** [comment]
I instantiated an ITwinAppIdHelper to my level and filled the App Id from the Details panel.

Kind regards
Dinos Ipiotis, MSc, MCIBSE.
Digital Delivery Leader
Sweco UK Limited | Ipswich
Telephone 01473231100
[Sweco logo]
For more information on how Sweco processes your personal data, please read here. <https://www.sweco.co.uk/privacy-statement/>

**Comment by Julot94** [comment]
Do you see some additional logs that could be related to this error? (from Unreal Output Log window)
any log with channel "**LogITwinHttp**", "**LogITwin**" or "**LogITwinCesium**" could be relevant here, as well as **LogHttpServerModule** and **LogHttpListener**

**Comment by DinosIpiotis** [comment]
The latest log I can see is the one attached, not sure where to find the rest. this is pulled from Saved\Logs under my project file. 
[iTwinSample.log](https://github.com/user-attachments/files/16279039/iTwinSample.log)

**Comment by Julot94** [comment]
Hello,
Can you please share a capture of your app settings from https://developer.bentley.com/apps?
Thanks
