### ISSUE TITLE
Error : Invalid Client_id 

### ISSUE THREAD

**Issue by AnantaVC** [iTwin/itwin-unreal-plugin#11]
Created native app in iTwin Platform 

 - Application type: Native 

  -Redirect URIs: http://localhost:3000/signin-callback 
 
Added Client app ID in “ITwinAppIdHelper” actor details 
Added Itwin Model ID in “iTwinImodel” actor details 
 
Unable to authorize after entering: iTwin Model ID in “iTwinImodel” actor details 
 
This error pops up in the browser authorization window 
 
![image](https://github.com/user-attachments/assets/bc0a1dbd-7797-4ba6-a489-df638691f175)

 

Kindly let us know how to troubleshoot this.

**Comment by AlexandreWalensa** [comment]
Hi AnantaVC, can you share a capture of your app settings from https://developer.bentley.com/apps?
