### ISSUE TITLE
Blueprint vs. C++ Project

### ISSUE THREAD

**Issue by Darkstar130** [iTwin/itwin-unreal-plugin#13]
Hi guys,

Will this plugin work for a non C++ project or does it have to have a generated VS project and be recompiled? I have tried to compile in a 5.3.2 project and it's missing depenencies. It's a brand new project. Error log didn't say what depency it was but it was from a iTwin .dll

**Comment by AlexandreWalensa** [comment]
Hi, the plugin should work for both c++ and blueprint projects.
Could you describe the steps to reproduce the issue? Thanks.
