### ISSUE TITLE
'Unauthorized' error relating to 4D schedules

### ISSUE THREAD

**Issue by MSeddonProicere** [iTwin/itwin-unreal-plugin#15]
Hi there,

I'm getting an error when trying to follow section 5 of your guide. I'm following exactly what it says but the schedule refuses to download.

I'm not sure what exactly is 'unauthorized' but as for my account, I'm admin so it should be on that side at least.

![image](https://github.com/user-attachments/assets/10fd7b9d-bd0e-4bdd-bceb-530db4527056)

**Comment by GhisBntly** [comment]
Hi,
The first error is "OK" (about the NextGen schedule), but the second one indeed is not.
Did you assign the scope "itwin-platform" to you app ID when setting it up?
What is the "Synced" date on your iModel, when looking in your project's "Manage iModel" web page?

**Comment by MSeddonProicere** [comment]
Hi,

Please find attached below what you asked for, to me it looks like everything is set up correctly to me on that front

![image](https://github.com/user-attachments/assets/cc7f0bfc-ac30-423e-b6c3-c70b0e79bb1f)
![image](https://github.com/user-attachments/assets/1662831e-4d59-49f2-80fb-b9fb46766015)
![image](https://github.com/user-attachments/assets/d0d53318-d37a-4fb4-a720-1475be449bb9)

**Comment by GhisBntly** [comment]
Hello,
Thanks for confirming this, basic stuff but one needs to cover all bases ^^
Since you reached section 5., I assume you can see the geometries of your model, right, only the schedule fails?

Last week I had one (maybe two) reports with the same symptom, which we are currently investigating (although I could never reproduce on my side). I will let you know what we find.

**Comment by MSeddonProicere** [comment]
No worries at all
Correct the geometries are showing perfectly fine, the authorisation browser pops up fine too. It is only the schedule that it is failing to authorise.

If it helps, please feel free to ask me to post anything you need relating to the issue to aid your investigation

Thanks!

**Comment by MSeddonProicere** [comment]
So i (kind of) managed to get it to find the schedule. At runtime, i have to update the IModel, then go to he Synchro4DSchedules component and press reset schedules, then go back up to the IModel and update it again, and it (sometimes) loads the schedule. 

Naturally this is good for in-engine stuff but i can't build anything around this which is unfortunate.

**Comment by GhisBntly** [comment]
Hello,
I made a fix for the new version just released (0.1.10) which I hope should work for you: a colleague who had the same problem no longer sees it with the new version.
The new version also brings important schedule-related improvements, and removes several limitations: please check the updated README when upgrading!
Let me know how it goes,

**Comment by MSeddonProicere** [comment]
Thanks so much! I can confirm this worked on my system. Sorry for the late reply!
