### ISSUE TITLE
Plugin does not seem to like being in the game folder rather than the Engine folder.

### ISSUE THREAD

**Issue by MSeddonProicere** [iTwin/itwin-unreal-plugin#17]
Hi there,

There seems to be an issue where the plugin I downloaded the 'ITwinForUnreal.zip' file (0.1.10 ver) and it does not like being inside of the game's plugins folder where i can add custom code, just in the engine/plugins/marketplace location where changes don't take effect 
(I'm trying to make a blueprint of the ITwiniModel to allow for a iTwin to be entered and then updated at runtime)

(Game/Plugins)
![image](https://github.com/user-attachments/assets/c0c74e79-ab66-4f61-a047-b7f951a35734)

(Engine/Plugins/Marketplace)
![image](https://github.com/user-attachments/assets/6bc8fd65-c431-4f77-b31e-ad17d33bc18a)

**Comment by MSeddonProicere** [comment]
Any updates?

**Comment by AlexandreWalensa** [comment]
Hi @MSeddonProicere, what is your version of visual studio?
Also, can you please give the complete build output log?
Thanks.
