### ISSUE TITLE
Growth Simulation Reversed in Unreal Engine SDK Plugin

### ISSUE THREAD

**Issue by VCGP-TIAANJ** [iTwin/itwin-unreal-plugin#19]
I noticed my growth simulation for my construction is reversed when I bring the i-twin model into unreal engine.
The example attached are from when you watch the video on Synchro Control (correct growth simulation) and the other is the Unreal Engine plugin, which is reversed. 

![2024-09-15_19h41_11](https://github.com/user-attachments/assets/25c487f5-1e7c-492e-91a7-9aaf7c0396f4)
![2024-09-15_19h39_46](https://github.com/user-attachments/assets/ec2009f0-3a6c-460a-87f3-672fd2b8428f)

Video recording of my screen can be found in link below:

https://we.tl/t-7h2WCl90s8

**Comment by GhisBntly** [comment]
Hello, and sorry for the reply delay!
I am indeed working on a batch of fixes, including this obvious Y axis inversion. You may also notice that "Remove" tasks are not handled properly, as well as "Maintenance" and "Temporary" tasks which have the "Simulate as Remove" flag set.
Regards,

**Comment by GhisBntly** [comment]
Closing as the mentioned fixes were included in release 0.1.11 from October 4th

**Comment by NimrodFriedmann** [comment]
[like]  Nimrod Friedmann reacted to your message:
________________________________
