### ISSUE TITLE
Still having issues with incorrect appearance profile displays

### ISSUE THREAD

**Issue by JPipe89** [iTwin/itwin-unreal-plugin#24]
Incorrect appearance profile displays and items not showing as they should within Synchro, see images![Image](https://github.com/user-attachments/assets/90ae9830-e4ca-4182-8598-5a9a5fe55dea)
![Image](https://github.com/user-attachments/assets/2ec436f2-d902-491e-819b-d759120226d5)

**Comment by GhisBntly** [comment]
Hello,
Indeed some "Remove" tasks still do not work: this is because the task has a null time extent, I did not anticipate that possibility, sorry!
I am fixing this case for the next version and will double-check for similar situations.
Best regards,

**Comment by GhisBntly** [comment]
Fixed in 0.1.12 (https://github.com/iTwin/itwin-unreal-plugin/releases/tag/0.1.12)
