### ISSUE TITLE
Package build error

### ISSUE THREAD

**Issue by MortonPriceBBV** [iTwin/itwin-unreal-plugin#6]
Hi i'm getting the following error when trying to package. 

This is using the latest plugin release on the 08/07/2024

UATHelper: Packaging (Windows): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows): Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" BBVHS2Flythough Win64 Development -Project="C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\BBVHS2Flythough.uproject" -Manifest="C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Intermediate\Build\Manifest.xml"  -remoteini="C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy"  -skipdeploy  -lo
g="C:\Users\jenso\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-BBVHS2Flythough-Win64-Development.txt"
UATHelper: Packaging (Windows): Log file: C:\Users\jenso\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-BBVHS2Flythough-Win64-Development.txt
UATHelper: Packaging (Windows): Creating makefile for BBVHS2Flythough (no existing makefile)
UATHelper: Packaging (Windows): Total execution time: 1.79 seconds
UATHelper: Packaging (Windows): Missing precompiled manifest for 'ITwinCesiumRuntime', 'C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\ITwinForUnreal\Intermediate\Build\Win64\UnrealGame\Development\ITwinCesiumRuntime\ITwinCesiumRuntime.precompiled'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in ITwinCesiumRuntime.build.cs to override. If part of a plugin, also check if its 'Type' is correct.
UATHelper: Packaging (Windows): Took 1.93s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\jenso\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-BBVHS2Flythough-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 4s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error

Please note i'm using multiple iModel blueprints as i'm bringing down iTwin data from multiple iModels that all join up.

![image](https://github.com/iTwin/itwin-unreal-plugin/assets/146174125/04c144d5-fa18-45b2-959f-ab423a0efe63)

**Comment by charleschandesris** [comment]
Hi Morton, 
Thanks for reporting. We are investigating this issue.
There is a workaround for this issue. You can copy the itwin unreal plugin to the plugins folder of your project.

**Comment by MortonPriceBBV** [comment]
Thank you

Do I also remove it from the 5.3 plugin folder, or do I leave it there?


Kind regards,
Morton Price
***@***.***
BIM Manager | Balfour Beatty VINCI | HS2
M: +44 (0) 73 8804 1455  |  ***@***.******@***.***>
www.balfourbeattyvinci.co.uk<http://www.balfourbeattyvinci.co.uk/>

***@***.***

**Comment by MortonPriceBBV** [comment]
Ok, i have copied the plugin into the project specific plugin folder, 
The build gets a lot further, but still fails to compile. this is the output log 

UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Tests\WebServicesTest.cpp(1067): error C3791: 'this' cannot be explicitly captured when the default capture mode is by copy (=)
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Tests\WebServicesTest.cpp(1111): error C3791: 'this' cannot be explicitly captured when the default capture mode is by copy (=)
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesStructs.h(55): error C7582: 'bUseOriginalColor': default member initializers for bit-fields requires at least '/std:c++20'
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesStructs.h(56): error C7582: 'bUseOriginalAlpha': default member initializers for bit-fields requires at least '/std:c++20'
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesStructs.h(68): error C7582: 'bGrowthSimulationBasedOnPercentComplete': default member initializers for bit-fields requires at least '/std:c++20'
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesStructs.h(70): error C7582: 'bGrowthSimulationPauseDuringNonWorkingTime': default member initializers for bit-fields requires at least '/std:c++20'
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesStructs.h(74): error C7582: 'bInvertGrowth': default member initializers for bit-fields requires at least '/std:c++20'
UATHelper: Packaging (Windows): C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\INCLUDE\ranges(11): warning STL4038: The contents of <ranges> are available only with C++20 or later.
UATHelper: Packaging (Windows): [10/33] Compile [x64] Module.ITwinRuntime.1.cpp
UATHelper: Packaging (Windows): [11/33] Compile [x64] Module.ITwinCesiumRuntime.12.cpp
UATHelper: Packaging (Windows): [12/33] Compile [x64] Module.ITwinCesiumRuntime.4.cpp
UATHelper: Packaging (Windows): [13/33] Compile [x64] Module.ITwinCesiumRuntime.2.cpp
UATHelper: Packaging (Windows): [14/33] Compile [x64] Module.ITwinCesiumRuntime.3.cpp
UATHelper: Packaging (Windows): [15/33] Compile [x64] Module.ITwinCesiumRuntime.8.cpp
UATHelper: Packaging (Windows): [16/33] Compile [x64] Module.ITwinCesiumRuntime.1.cpp
UATHelper: Packaging (Windows): [17/33] Compile [x64] Module.ITwinCesiumRuntime.5.cpp
UATHelper: Packaging (Windows): [18/33] Compile [x64] Module.ITwinCesiumRuntime.11.cpp
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumTileExcluderAdapter.cpp(24): warning C4996: 'AITwinCesiumGeoreference::GetGeoTransforms': Use transformation functions on AITwinCesiumGeoreference and UITwinCesiumWgs84Ellipsoid instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): [19/33] Resource Default.rc2
UATHelper: Packaging (Windows): [20/33] Copy OpenImageDenoise.dll
UATHelper: Packaging (Windows): [21/33] Copy NvmlWrapper.dll
UATHelper: Packaging (Windows): [22/33] Copy get_ps_servers.bat
UATHelper: Packaging (Windows): [23/33] Copy tbb.dll
UATHelper: Packaging (Windows): [24/33] Copy tbbmalloc.dll
UATHelper: Packaging (Windows): [25/33] Copy d3d12SDKLayers.dll
UATHelper: Packaging (Windows): [26/33] Copy D3D12Core.dll
UATHelper: Packaging (Windows): [27/33] Copy tbbmalloc.pdb
UATHelper: Packaging (Windows): [28/33] Copy tbb.pdb
UATHelper: Packaging (Windows): [29/33] Copy get_ps_servers.sh
UATHelper: Packaging (Windows): [30/33] Copy tbb12.dll
UATHelper: Packaging (Windows): [31/33] Compile [x64] Module.ITwinCesiumRuntime.10.cpp
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumGltfPointsSceneProxy.cpp(54): warning C4996: 'FRenderResource::InitResource': InitResource now requires a command list. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumGltfPointsSceneProxy.cpp(55): warning C4996: 'FRenderResource::InitResource': InitResource now requires a command list. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(33): warning C4996: 'RHICreateBuffer': RHICreateBuffer is deprecated. Use FRHICommandListBase::CreateBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(40): warning C4996: 'RHILockBuffer': RHILockBuffer is deprecated. Use FRHICommandListBase::LockBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(54): warning C4996: 'RHIUnlockBuffer': RHIUnlockBuffer is deprecated. Use FRHICommandListBase::UnlockBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(144): warning C4996: 'RHICreateBuffer': RHICreateBuffer is deprecated. Use FRHICommandListBase::CreateBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(151): warning C4996: 'RHILockBuffer': RHILockBuffer is deprecated. Use FRHICommandListBase::LockBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(156): warning C4996: 'RHIUnlockBuffer': RHIUnlockBuffer is deprecated. Use FRHICommandListBase::UnlockBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): Total time in Parallel executor: 421.00 seconds
UATHelper: Packaging (Windows): Total execution time: 426.06 seconds
UATHelper: Packaging (Windows): Took 426.22s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\jenso\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-BBVHS2Flythough-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 7m 8s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by charleschandesris** [comment]
Hi Morton,
Could you check this:
Enable C++20 support; this can be done by adding/updating this line in your *.Target.cs files:
DefaultBuildSettings = BuildSettingsVersion.V4;

**Comment by MortonPriceBBV** [comment]
> Hi Morton, Could you check this: Enable C++20 support; this can be done by adding/updating this line in your *.Target.cs files: DefaultBuildSettings = BuildSettingsVersion.V4;

Ok i have updated the script from V3 to V4, however i still still a compiler error. Error report below if it helps 

LogUObjectHash: Compacting FUObjectHashTables data took   0.49ms
LogTurnkeySupport: Project requires temp target (GeoReferencing plugin is enabled)
LogLauncherProfile: Unable to use promoted target - ../../../../../../Users/jenso/Documents/Unreal Projects/BBVHS2Flythough - New 3.0 - Copy/Binaries/Win64/UnrealGame.target does not exist.
LogMonitoredProcess: Running Serialized UAT: [ cmd.exe /c ""C:/Program Files/Epic Games/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat"  -ScriptsForProject="C:/Users/jenso/Documents/Unreal Projects/BBVHS2Flythough - New 3.0 - Copy/BBVHS2Flythough.uproject" Turnkey -command=VerifySdk -platform=Win64 -UpdateIfNeeded -EditorIO -EditorIOPort=61875  -project="C:/Users/jenso/Documents/Unreal Projects/BBVHS2Flythough - New 3.0 - Copy/BBVHS2Flythough.uproject" BuildCookRun -nop4 -utf8output -nocompileeditor -skipbuildeditor -cook  -project="C:/Users/jenso/Documents/Unreal Projects/BBVHS2Flythough - New 3.0
 - Copy/BBVHS2Flythough.uproject"  -unrealexe="C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\Win64\UnrealEditor-Cmd.exe" -platform=Win64 -installed -stage -archive -package -build -pak -iostore -compressed -prereqs -archivedirectory="C:/Users/jenso/Desktop/BBV Flythorugh Test Build Jun24 5.3" -clientconfig=Development" -nocompile -nocompileuat ]
UATHelper: Packaging (Windows): Running AutomationTool...
UATHelper: Packaging (Windows): Using bundled DotNet SDK version: 6.0.302
UATHelper: Packaging (Windows): Starting AutomationTool...
UATHelper: Packaging (Windows): Parsing command line: -ScriptsForProject="C:/Users/jenso/Documents/Unreal Projects/BBVHS2Flythough - New 3.0 - Copy/BBVHS2Flythough.uproject" Turnkey -command=VerifySdk -platform=Win64 -UpdateIfNeeded -EditorIO -EditorIOPort=61875 -project="C:/Users/jenso/Documents/Unreal Projects/BBVHS2Flythough - New 3.0 - Copy/BBVHS2Flythough.uproject" BuildCookRun -nop4 -utf8output -nocompileeditor -skipbuildeditor -cook -project="C:/Users/jenso/Documents/Unreal Projects/BBVHS2Flythough - New 3.0 - Copy/BBVHS2Flythough.uproject" -unrealexe="C:\Program Files\Epic Games\UE_5.3
\Engine\Binaries\Win64\UnrealEditor-Cmd.exe" -platform=Win64 -installed -stage -archive -package -build -pak -iostore -compressed -prereqs -archivedirectory="C:/Users/jenso/Desktop/BBV Flythorugh Test Build Jun24 5.3" -clientconfig=Development -nocompile -nocompileuat
UATHelper: Packaging (Windows): Initializing script modules...
UATHelper: Packaging (Windows): Total script module initialization time: 0.25 s.
UATHelper: Packaging (Windows): Executing commands...
UATHelper: Packaging (Windows): Installed Sdk validity:
UATHelper: Packaging (Windows): Win64: (Status=Valid, MinAllowed_Sdk=10.0.00000.0, MaxAllowed_Sdk=10.9.99999.0, Current_Sdk=10.0.22621.0, Allowed_AutoSdk=10.0.18362.0, Current_AutoSdk=, Flags="InstalledSdk_ValidVersionExists")
UATHelper: Packaging (Windows): Scanning for envvar changes...
UATHelper: Packaging (Windows): ... done! 
UATHelper: Packaging (Windows): Cleaning Temp Paths...
UATHelper: Packaging (Windows): BUILD SUCCESSFUL
UATHelper: Packaging (Windows): Setting up ProjectParams for C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\BBVHS2Flythough.uproject
UATHelper: Packaging (Windows): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows): Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" BBVHS2Flythough Win64 Development -Project="C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\BBVHS2Flythough.uproject" -Manifest="C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Intermediate\Build\Manifest.xml"  -remoteini="C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy"  -skipdeploy  -lo
g="C:\Users\jenso\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-BBVHS2Flythough-Win64-Development.txt"
UATHelper: Packaging (Windows): Log file: C:\Users\jenso\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-BBVHS2Flythough-Win64-Development.txt
UATHelper: Packaging (Windows): Creating makefile for BBVHS2Flythough (manifest 'C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Intermediate\Build\Manifest.xml' not found)
UATHelper: Packaging (Windows): Writing manifest to C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Intermediate\Build\Manifest.xml
UATHelper: Packaging (Windows): Building BBVHS2Flythough...
UATHelper: Packaging (Windows): Using Visual Studio 2022 14.40.33811 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
UATHelper: Packaging (Windows): Determining max actions to execute in parallel (14 physical cores, 20 logical cores)
UATHelper: Packaging (Windows):   Executing up to 14 processes, one per physical core
UATHelper: Packaging (Windows):   Requested 1.5 GB memory per action, 3.6 GB available: limiting max parallel actions to 2
UATHelper: Packaging (Windows): ------ Building 21 action(s) started ------
UATHelper: Packaging (Windows): [1/21] Compile [x64] PCH.ITwinCesiumRuntime.cpp
UATHelper: Packaging (Windows): Detected compiler newer than Visual Studio 2022, please update min version checking in WindowsPlatformCompilerSetup.h
UATHelper: Packaging (Windows): [2/21] Compile [x64] SharedPCH.Core.Cpp20.cpp
UATHelper: Packaging (Windows): Detected compiler newer than Visual Studio 2022, please update min version checking in WindowsPlatformCompilerSetup.h
UATHelper: Packaging (Windows): [3/21] Compile [x64] SharedPCH.Engine.Cpp20.cpp
UATHelper: Packaging (Windows): Detected compiler newer than Visual Studio 2022, please update min version checking in WindowsPlatformCompilerSetup.h
LogDerivedDataCache: C:/Users/jenso/AppData/Local/UnrealEngine/Common/DerivedDataCache: Maintenance finished in +00:00:14.140 and deleted 0 files with total size 0 MiB and 0 empty folders. Scanned 7264 files in 9188 folders with total size 1619 MiB.
UATHelper: Packaging (Windows): [4/21] Compile [x64] Module.ITwinRuntime.2.cpp
UATHelper: Packaging (Windows): [5/21] Compile [x64] Module.ITwinRuntime.1.cpp
UATHelper: Packaging (Windows): [6/21] Compile [x64] Module.ITwinRuntime.3.cpp
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Tests\WebServicesTest.cpp(700): error C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesImport.cpp(623): error C4101: '$S1553': unreferenced local variable
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesImport.cpp(623): error C4101: '$S1559': unreferenced local variable
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesImport.cpp(623): error C4101: '$S1557': unreferenced local variable
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Timeline\SchedulesImport.cpp(617): error C4101: '$S1555': unreferenced local variable
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ThirdParty\include\httpmockserver\port_searcher.h(26): error C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ThirdParty\include\httpmockserver\port_searcher.h(26): note: the template instantiation context (the oldest one first) is
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinRuntime\Private\Tests\WebServicesTest.cpp(701): note: see reference to function template instantiation 'std::unique_ptr<httpmock::MockServer,std::default_delete<httpmock::MockServer>> httpmock::getFirstRunningMockServer<FITwinMockServer>(unsigned int,unsigned int)' being compiled
UATHelper: Packaging (Windows): [7/21] Compile [x64] Module.ITwinCesiumRuntime.6.cpp
UATHelper: Packaging (Windows): [8/21] Compile [x64] Module.ITwinCesiumRuntime.9.cpp
UATHelper: Packaging (Windows): [9/21] Compile [x64] Module.ITwinCesiumRuntime.10.cpp
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumGltfPointsSceneProxy.cpp(54): warning C4996: 'FRenderResource::InitResource': InitResource now requires a command list. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumGltfPointsSceneProxy.cpp(55): warning C4996: 'FRenderResource::InitResource': InitResource now requires a command list. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(33): warning C4996: 'RHICreateBuffer': RHICreateBuffer is deprecated. Use FRHICommandListBase::CreateBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(40): warning C4996: 'RHILockBuffer': RHILockBuffer is deprecated. Use FRHICommandListBase::LockBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(54): warning C4996: 'RHIUnlockBuffer': RHIUnlockBuffer is deprecated. Use FRHICommandListBase::UnlockBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(144): warning C4996: 'RHICreateBuffer': RHICreateBuffer is deprecated. Use FRHICommandListBase::CreateBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(151): warning C4996: 'RHILockBuffer': RHILockBuffer is deprecated. Use FRHICommandListBase::LockBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumPointAttenuationVertexFactory.cpp(156): warning C4996: 'RHIUnlockBuffer': RHIUnlockBuffer is deprecated. Use FRHICommandListBase::UnlockBuffer instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): [10/21] Compile [x64] Module.ITwinCesiumRuntime.1.cpp
UATHelper: Packaging (Windows): [11/21] Compile [x64] Module.ITwinCesiumRuntime.7.cpp
UATHelper: Packaging (Windows): [12/21] Compile [x64] Module.BBVHS2Flythough.cpp
UATHelper: Packaging (Windows): [13/21] Compile [x64] Module.ITwinCesiumRuntime.8.cpp
UATHelper: Packaging (Windows): [14/21] Compile [x64] Module.ITwinCesiumRuntime.11.cpp
UATHelper: Packaging (Windows): C:\Users\jenso\Documents\Unreal Projects\BBVHS2Flythough - New 3.0 - Copy\Plugins\ITwinForUnreal\Source\ITwinCesiumRuntime\Private\ITwinCesiumTileExcluderAdapter.cpp(24): warning C4996: 'AITwinCesiumGeoreference::GetGeoTransforms': Use transformation functions on AITwinCesiumGeoreference and UITwinCesiumWgs84Ellipsoid instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: Packaging (Windows): [15/21] Compile [x64] Module.ITwinCesiumRuntime.12.cpp
UATHelper: Packaging (Windows): [16/21] Compile [x64] Module.ITwinCesiumRuntime.2.cpp
UATHelper: Packaging (Windows): [17/21] Compile [x64] Module.ITwinCesiumRuntime.4.cpp
UATHelper: Packaging (Windows): [18/21] Compile [x64] Module.ITwinCesiumRuntime.3.cpp
UATHelper: Packaging (Windows): [19/21] Compile [x64] Module.ITwinCesiumRuntime.5.cpp
UATHelper: Packaging (Windows): Total time in Parallel executor: 457.81 seconds
UATHelper: Packaging (Windows): Total execution time: 462.51 seconds
UATHelper: Packaging (Windows): Took 462.86s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\jenso\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-BBVHS2Flythough-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 7m 45s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by AlexandreWalensa** [comment]
Hi Morton, in your last message I see 2 kinds of errors:
- error C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
  We have a fix coming for this error.
- error C4101: '$S1553': unreferenced local variable
  This is a compiler bug that occurs with Visual Studio 2022 v17.10.
  We recommend downgrading to v17.9 or see if an update of 17.10 has been released by Microsoft which would fix the issue.
