### ISSUE TITLE
Multiple iModels  

### ISSUE THREAD

**Issue by MortonPriceBBV** [iTwin/itwin-unreal-plugin#7]
I seem to be struggling using multiple iModels since the latest plugin was updated. 
My levels contain multiple iModels, that all stream different iTwin models
When trying to play the level, my web browser opens 10 different tabs, each one request to choose my Bentley account and accept the Bentley ToS. 
When accepting I get  I'm greeted with a local host hhhmmm can'y reach this page message, and nothing loads in UE5.  Please see attached screen shots. 

The older 3DFT plugin, was set up for me with help from a Bentley Dev, who added the authorisation directing into my UE5 Hud. this then prevented the separate web browser from opening up outside of UE5.  Is this possible to replicate using the new plugin, and if so can any developer help me add that ability in my app. 

Thank you

![Screenshot 2024-07-10 0833461](https://github.com/iTwin/itwin-unreal-plugin/assets/146174125/61069af5-86de-41b0-8789-3c82197620fb)
![Screenshot 2024-07-10 083305](https://github.com/iTwin/itwin-unreal-plugin/assets/146174125/1338ea47-959d-447b-9cea-a94f5acba8e3)

**Comment by Julot94** [comment]
Hi Morton,
I could fix the fact multiple tabs were open and failed (fix available in coming update, next week)
However, there will still be one tab opened (with no required interaction if a previous authorization can be found on your machine)
