### ISSUE TITLE
How can ı active the plugin ?

### ISSUE THREAD

**Issue by 4dnika** [iTwin/itwin-unreal-plugin#9]
I tried to follow the steps in this link, but I could not find ITwinAppIdHelper and could not proceed beyond the 3rd step of the 2nd title.  Is there a chance to make a video or a meeting on how to activate this plugin?

**Comment by DinosIpiotis** [comment]
You will need to create an app as per the instructions:

3. Configure access to the iTwin Platform
Create and configure your iTwin Platform account:

Go to the [iTwin Platform developer portal](https://developer.bentley.com/) and create an account.
Go to [My Models](https://developer.bentley.com/my-imodels/) and create a new iModel.
Go to [My Apps](https://developer.bentley.com/my-apps/) and [register a new iTwin App](https://developer.bentley.com/tutorials/quickstart-web-and-service-apps/#12-register-your-application):
Application type: Native
Redirect URIs: http://localhost:3000/signin-callback

**Comment by 4dnika** [comment]
ı did these steps, I cant figure out remain steps

**Comment by Julot94** [comment]
Hello,
The ITwinAppIDHelper can be found from Unreal's content browser, in Plugins > iTwin for Unreal C++ Classes > ITwinRuntime > Public, as shown in the attached screenshot.
Just drag & drop this in the viewport, and then fill the **![iTwinAppIDHelper](https://github.com/user-attachments/assets/0e90d886-8652-47b9-83ec-37f763a5a815)** property from the _Details_ panel.

**Comment by 4dnika** [comment]
Hello,

I couldn't see Plugins folder in content browser in ue5.3 altough  I added Itwin plugin and  ticked itwin plugin. ı dont understand why ı cant find ItwinappIdHelper.
________________________________
Gönderen: Julien Desreumaux ***@***.***>
Gönderildi: 17 Temmuz 2024 Çarşamba 07:04
Kime: iTwin/itwin-unreal-plugin ***@***.***>
Bilgi: 4dnika ***@***.***>; Author ***@***.***>
Konu: Re: [iTwin/itwin-unreal-plugin] How can ı active the plugin ? (Issue #9)


Hello,
The ITwinAppIDHelper can be found from Unreal's content browser, in Plugins > iTwin for Unreal C++ Classes > ITwinRuntime > Public, as shown in the attached screenshot.
Just drag & drop this in the viewport, and then fill the iTwinAppIDHelper.jpg (view on web)<https://github.com/user-attachments/assets/0e90d886-8652-47b9-83ec-37f763a5a815> property from the Details panel.

**Comment by AlexandreWalensa** [comment]
Hi 4dnika, in the "settings" button on the top right of the content browser window, please make sure to enable:
"show c++ classes"
"show plugin content"
"show engine content"
